### ISSUE TITLE
Full Map is the Wrong Map

### ISSUE THREAD

**Issue by FMastro** [Ceddini/CoreKeeperMapTool#23] opened 2023-01-04 01:29 UTC
I loaded an earlier map, then later uploaded the right map I wanted. However, when I go to reveal the full map, it's showing the wrong one that doesn't match the one I was just looking at in the normal view. I probably changed maps around 5 or 6 times prior.  I tried a new browser, I get the same odd full map that doesn't match what I uploaded.

Also if you load a map file, then do load preview map, then try and upload the same map file again it doesn't re-load the map. Have to switch to a different file and then back. The upload control won't register a new file if it's the same name.

**Comment by Ceddini** [comment] 2023-02-01 11:39
Recently switched out the example map with a fully revealed map that includes the desert, so I've removed the "Full Map" button. That was just an image with all the biomes revealed so that people knew what to look for.

You shouldn't need to load the same map file, there is a refresh button
![image](https://user-images.githubusercontent.com/21086465/216032513-88eb64cf-c6c4-427c-a245-0e8e46374434.png)

Loading the same map might be a browser limitation, but I can look into how to change it. I'm gonna close this issue, since it currently works "as intended", even if it's not perfect :)

**Closed by Ceddini** 2023-02-01 11:39 UTC
